baseURL = 'http://blog.yangwenjian.cn/'
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "ç°¡"

theme = 'virgo'
hasCJKLanguage = true
summaryLength = 80    # default 70
paginate = 24         # better 4 * 3 * times
enableGitInfo = true

[params]
    # active fadeIn animate when load page
    hasActiveAnimate = true      

    # active cool style, be cool but take up more resources, and
    # if you want to replace default background image, just 
    # rename it `default.jpg` and place it into `/static/imgs/bg` dir, like `/static/imgs/bg/default.jpg`.
    hasActiveCool = false

    # For a better experience, we use localstorage to keep theme dark status, so
    # if you set dark as `true` but has no effect, you
    # should clear local storage of current site. And
    # in general, there has no any questions when you use it firstly.
    dark = true

    # Fold/Unfold code blocks, default `false`, and
    # if `true` ï¼Œall code blocks will be folded when page load.
    # It will be always true in Mobile view no matter what's your setting.
    hasFoldAllCodeBlocks = true

    # active english view, default chinese
    en = false

    slogan = 'å¤§é“è‡³ç®€'        # your site slogan below title

    # like the following items that you need create a relative markdown file
    # Search - search.md
    # Nav - nav.md 
    # Archive - archive.md
    # About - about.md or about/index.md
    # Idea posts/idea.md 
    # Wiki - posts/wiki.md
    [params.menu]
        [params.menu.00]
            active = false
            path = '/nav'
            en = 'Nav'
            zh = 'å¯¼èˆª'
            icon = 'ğŸ¯'
        [params.menu.11]
            active = true
            path = '/search'
            en = 'Search'
            zh = 'æœç´¢'
            icon = 'ğŸ”'
        [params.menu.22]
            active = true
            path = '/posts'
            en = 'Posts'
            zh = 'æ–‡ç« '
            icon = 'ğŸ“œ'
        [params.menu.33]
            active = true
            path = '/archive'
            en = 'Archive'
            zh = 'å½’æ¡£'
            icon = 'ğŸ‰'
        [params.menu.44]
            active = true	
            path = '/wiki'
            en = 'Wiki'
            zh = 'ç™¾ç§‘'
            icon = 'ğŸš€'
        [params.menu.55]
            active = true
            path = '/about'
            en = 'About'
            zh = 'å…³äº'
            icon = 'ğŸŒ'

    [params.svg]
        color = '#6c757d'                   # icon color of breadcrumb '#666'  # '#5a29e4' 
    
    [params.img]
        # Img of home page - if not jpg, rename it, and
        # place it inio `static/imgs/` dir
        # In-built : lightcolor, girl, wukong, and tux
        # src = 'wukong'
        width = 999
        # and if not want to show img but some words, just 
        # comment `src = 'xxx'`, and input your words:
        #words = "Stay hungry, Stay foolish. Your time is limited, so don't waste it living someone else's life. Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary. -- Steve Jobs."
        words = "ä¹¾ä¸ºå¤©ï¼Œå¤ä¸ºåœ°ï¼Œæ°´é›·å±¯ï¼Œå±±æ°´è’™ï¼›<br/>æ°´å¤©éœ€ï¼Œå¤©æ°´è®¼ï¼Œåœ°æ°´å¸ˆï¼Œæ°´åœ°æ¯”ï¼›é£å¤©å°ç•œï¼Œå¤©æ³½å±¥ï¼Œåœ°å¤©æ³°ï¼Œå¤©åœ°å¦ï¼›å¤©ç«åŒäººï¼Œç«å¤©å¤§æœ‰ï¼Œåœ°å±±è°¦ï¼Œé›·åœ°è±«ï¼›æ³½é›·éšï¼Œå±±é£è›Šï¼Œåœ°æ³½ä¸´ï¼Œé£åœ°è§‚ï¼›ç«é›·å™¬å—‘ï¼Œå±±ç«è´²ï¼Œå±±åœ°å‰¥ï¼Œåœ°é›·å¤ï¼›å¤©é›·æ— å¦„ï¼Œå±±å¤©å¤§ç•œï¼Œå±±é›·é¢ï¼Œæ³½é£å¤§è¿‡ï¼›åä¸ºæ°´ï¼Œç¦»ä¸ºç«ï¼Œæ³½å±±å’¸ï¼Œé›·é£æ’ï¼›å¤©å±±éï¼Œé›·å¤©å¤§å£®ï¼Œç«åœ°æ™‹ï¼Œåœ°ç«æ˜å¤·ï¼›é£ç«å®¶äººï¼Œç«æ³½ç½ï¼Œæ°´å±±è¹‡ï¼Œé›·æ°´è§£ï¼›å±±æ³½æŸï¼Œé£é›·ç›Šï¼Œæ³½å¤©å¤¬ï¼Œå¤©é£å§¤ï¼›æ³½åœ°èƒï¼Œåœ°é£å‡ï¼Œæ³½æ°´å›°ï¼Œæ°´é£äº•ï¼›æ³½ç«é©ï¼Œç«é£é¼ï¼Œéœ‡ä¸ºé›·ï¼Œè‰®ä¸ºå±±ï¼›é£å±±æ¸ï¼Œé›·æ³½å½’å¦¹ï¼Œé›·ç«ä¸°ï¼Œç«å±±æ—…ï¼›å·½ä¸ºé£ï¼Œå…‘ä¸ºæ³½ï¼Œé£æ°´æ¶£ï¼Œæ°´æ³½èŠ‚ï¼›é£æ³½ä¸­å­šï¼Œé›·å±±å°è¿‡ï¼Œæ°´ç«æ—¢æµï¼Œç«æ°´æœªæµ"

    [params.contact]
        icp = 'å¤©è¡Œå¥ï¼Œå›å­ä»¥è‡ªå¼ºä¸æ¯ï¼›åœ°åŠ¿å¤ï¼Œå›å­ä»¥åšå¾·è½½ç‰©'          # beian number
        # icplink = '//beian.miit.gov.cn'
        # weibo = '6867589681'                # e.g. https://weibo.com/u/6867589681
        # wechat = 'imgs/bg/wechat.jpg'       # Wechat QR, choose your path
        email = 'jain_y@126.com'
        github = 'wjain'              # e.g. https://github.com/loveminimal
        bilibili = '488182320'               # e.g. https://space.bilibili.com/11608450
        # twitter = 'loveminimal'             # e.g. https://twitter.com/loveminimal
        # facebook = 'loveminimal'            # e.g. https://facebook.com/loveminimal
        # youtube = 'loveminimal'             # e.g. https://youtube.com/user/loveminimal
        color = '#696969'                   # icon color of contact #5d2f86

[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        style = "github"
        lineNos = false
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true